"ui.background" = { bg = "gray4" }

"ui.text" = { fg = "gray10" }
"ui.text.info" = { fg = "gray10" }
"ui.text.focus" = { fg = "blue" }
"ui.text.inactive" = { fg = "gray7" }

"ui.selection" = { bg = "gray6" }

"ui.cursor" = { fg = "gray7", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "blue", modifiers = ["reversed"] }
"ui.cursor.match" = { underline = { color = "gray10", style = "line" } }

"ui.linenr" = { fg = "gray6" }
"ui.linenr.selected" = { fg = "gray7" }

"ui.statusline" = { bg = "gray2", fg = "gray7"}

"ui.highlight" = { bg = "gray5" }
"ui.window" = { fg = "gray2" }
"ui.help" = { bg = "gray2" }

"ui.virtual.jump-label" = { fg = "orange" }

"ui.menu" = { bg = "gray2" }
"ui.menu.selected" = { bg = "gray6" }

"ui.popup" = { bg = "gray2" }
"ui.popup.info" = {bg = "gray2", fg = "blue" }

"ui.statusline.normal" = { bg = "blue", fg = "gray2" }
"ui.statusline.insert" = { bg = "red", fg = "gray2" }
"ui.statusline.select" = { bg = "green", fg = "gray2" }

"ui.virtual.indent-guide" = { fg = "gray6" }
"ui.virtual.inlay-hint" = { fg = "saturatedGray" }

"diagnostic" = { underline = { color = "red", style = "curl" }, modifiers = ["dim"] }
"diagnostic.hint" = { underline = { color = "gray10", style = "curl" } }
"diagnostic.info" = { underline = { color = "blue", style = "curl" } }
"diagnostic.warning" = { underline = { color = "yellow", style = "curl" } }
"diagnostic.error" = { underline = { color = "red", style = "curl" } }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }

"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "blue" }
"hint" = { fg = "gray10" }

"attribute" = { fg = "red" }
"tag" = { fg = "red" }

"variable" = { fg = "lightRed" }
"variable.builtin" = { fg = "yellow" }
"variable.parameter" = { fg = "pink" }
"variable.other" = { fg = "gray10" }

"type" = { fg = "yellow" }
"type.builtin" = { fg = "orange" }
"type.parameter" = { fg = "yellow" }

"special" = { fg = "orange" }

"constant" = { fg = "orange" }
"constant.character" = { fg = "cyan" }

"string" = { fg = "green" }
"string.special.symbol" = { fg = "cyan" }

"comment" = { fg = "saturatedGray" }

"constructor" = { fg = "yellow" }

"punctuation" = { fg = "cyan" }
"punctuation.bracket" = { fg = "gray7" }
"punctuation.special" = { fg = "cyan" }

"keyword" = { fg = "cyan" }
"keyword.operator" = { fg = "cyan" }
"keyword.function" = { fg = "purple" }
"keyword.control" = { fg = "cyan" }
"keyword.storage" = { fg = "purple" }
"keyword.control.import" = { fg = "cyan" }

"function" = { fg = "blue" }
"operator" = { fg = "cyan" }

"diff.plus" = { fg = "green" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "blue" }

[palette]
lightRed = "#ff98a4"
red = "#ff757f"
darkRed = "#ff5370"
lightOrange = "#f8b576"
orange = "#ff966c"
darkOrange = "#fc7b7b"
yellow = "#ffc777"
green = "#c3e88d"
lightTeal = "#7af8ca"
teal = "#3ad7c7"
lightCyan = "#b4f9f8"
cyan = "#78dbff"
sky = "#60bdff"
blue = "#7cafff"
darkBlue = "#3d6fe0"
darkestBlue = "#3b63cf"
indigo = "#af9fff"
purple = "#c4a2ff"
pink = "#fca7ea"
darkPink = "#fd8aca"
saturatedGray = "#7a88cf"
desaturatedGray = "#979bb6"
gray11 = "#d5def8"
gray10 = "#c8d3f5"
gray9 = "#b4c2f0"
gray8 = "#a9b8e8"
gray7 = "#828bb8"
gray6 = "#444a73"
gray5 = "#2f334d"
gray4 = "#222436"
gray3 = "#1e2030"
gray2 = "#191a2a"
gray1 = "#131421"
